name: Sanity
on: [push]
jobs:
  SanityOnMulti:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: s-weigand/setup-conda@v1
        with:
            python-version: '3.10'
        
      - run: python3 -m venv .venv
      - run: >
          .venv/bin/python -m pip install 
          "pytest<8.1"
          "itk>=5.3.0"
          "matplotlib>=3.7.0"
          "numpy>=1.25"
          "pandas>=2.0.0"
          "pydicom>=2.4.0"
          "pywavelets>=1.4.0"
          "ray>=2.7.0"
          "scikit-image=0.20.0"
          "scipy>=1.11"
          "typing-extensions>=4.10"
      - run: .venv/bin/python -m pytest test
